# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - api-tipsandtrick

on:
  push:
    branches:
      - main
    paths:
      - "express_static"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "api-tipsandtrick"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_7ed82c70c1704d838049bfae39cc1a22 }}
          package: .
