name: Deploy to Static Website on Azure Storage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the code"
        uses: actions/checkout@main

      - name: "Deploy to Static Website on Azure Blob Storage"
        uses: tibor19/static-website-deploy@v1
        with:
          enabled-static-website: "true"
          folder: institucional
          connection-string: ${{ secrets.CONNECTION_STRING }}
